#!/bin/bash

echo "========================================="
echo "  VERIFICAR CONTRASEÑA DEL ADMIN"
echo "========================================="
echo ""

echo "El hash almacenado en la base de datos es:"
mysql -u campus2023 -pcampus2023 -s -N -e "USE logitrack_db; SELECT password FROM usuario WHERE username = 'admin';"

echo ""
echo "Según el archivo data.sql, la contraseña debería ser: admin123"
echo ""
echo "========================================="
echo "  PRUEBA ESTAS CONTRASEÑAS:"
echo "========================================="
echo ""
echo "En: http://localhost:8080/logitrack/"
echo ""
echo "Usuario: admin"
echo "Prueba con estas contraseñas (una por una):"
echo ""
echo "  1. admin123"
echo "  2. Admin123"
echo "  3. Admin123!"
echo "  4. admin"
echo "  5. password"
echo ""
echo "Si NINGUNA funciona, vamos a actualizar la contraseña."
echo ""
